# Use postgres/example user/password credentials
version: '3.8'

services:

  postgres:
    container_name: postgres_beeai
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - dockernet

  pgadmin:
    container_name: pgadmin_beeai
    image: dpage/pgadmin4:5.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    user: root
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - dockernet

  django:
    build:
      dockerfile:  Dockerfile
    container_name: django_beeai
    command: poetry run python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}
    volumes:
      - ./:/usr/src/beeaiapp
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - dockernet



networks:
    dockernet:

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  redis_conf:

