# Generated by Django 4.2.6 on 2023-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=250)),
                ('question_created_at', models.DateTimeField(db_comment='date from jservice.io API')),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
    ]
