# Generated by Django 4.2.6 on 2023-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomquestion',
            old_name='question_created_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='randomquestion',
            name='answer',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='randomquestion',
            name='question',
            field=models.CharField(max_length=350),
        ),
    ]
