# Generated by Django 4.2.6 on 2023-10-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jservice', '0002_rename_question_created_at_randomquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquestion',
            name='question_id',
            field=models.IntegerField(unique=True),
        ),
    ]
